[Model]

planning_horizon = 20

discount_rate = 7.0

time_step_duration = 1

zones = ["Zone1"]

resource_types = ["Coal", "Gas", "Solar", "Wind"]

data_dir = "data"

results_dir = "results"

[Solver]

solver_type = "HiGHS"

solver_options = {}

[Input_Data]

demand_data_file = ""

generator_data_file = ""

